trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: BatchScript@1
  inputs:
    filename: 'power.bat'
    arguments: '3 4'

- task: Bash@3
  inputs:
    filePath: 'calc.bat'
    arguments: '100 90'